### ISSUE TITLE
关于软件仿真环境

### ISSUE THREAD

**Issue by pointerliu** [Clo91eaf/PUA-MIPS#1]
注意到Makefile中使用了`TEST_TOP=../../PUA-MIPS-TEST`, 看起来项目有些缺失，请问可以分享一下使用的仿真环境吗？

**Comment by Clo91eaf** [comment]
非常抱歉, 这个项目已经年久失修, 原先的仿真环境已经被丢到不知道哪去了. 我们的仿真环境在比赛结束后被重构成HDU计算机组成原理大作业的一部分, 或许你可以在这个项目上看看魔改一下:https://github.com/Ciliphen/PUA-RISCV
不过我不建议你对复现这个项目抱有太大期待, 更好的参考方法是看看架构和里面一些关键部件的实现吧

**Comment by pointerliu** [comment]
好的谢谢 :)

**Comment by pointerliu** [comment]
您好，想再请教您一些问题。

我注意到PUA-MIPS早期设计是使用的带有握手信号的SRAM接口，但是soc-simulator使用的AXI接口，所以我猜测您早期设计并没有接入到软件仿真中。那您是用的龙芯杯提供的cde环境吗，但是好像只有loongarch的cde环境带有SRAM接口，mips的cde没有提供，**所以想请教一下您早期是怎么测试握手信号SRAM接口的**。

非常感谢！

**Comment by pointerliu** [comment]
哦哦，我找到cde环境了，非常感谢 :+1:
